language: c

compiler: gcc

env:
    matrix:
        - SDK_TARGET=tools
        - SDK_TARGET=xtensa
        - SDK_TARGET=x86
        - SDK_TARGET=arm

build:
    cache: false
    pre_ci_boot:
        image_name: zephyrprojectrtos/ci
        image_tag: v0.4-rc1
        pull: true
        options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"

    ci:
      - touch TEST.${SDK_TARGET}
      - >
          if [ "${IS_GIT_TAG}" = "true" ]; then
            sudo -E sh -c 'echo "IS_GIT_TAG=true" >> $JOB_STATE/sdk.env'
            export S3_PATH="s3://incoming.zephyrproject.org";
            aws s3 cp TEST.* ${S3_PATH}/tests/;
            aws s3 ls ${S3_PATH}/tests/
          fi

integrations:
  generic:
    - integrationName: aws_s3_simple

